### ISSUE TITLE
panic: runtime error: index out of range [8] with length 0

### ISSUE THREAD

**Issue by ludoux** [ludoux/qbittorrent-torrents-exporter#11]
使用 v0.3.3 报错：
```
PS D:\qb> D:\qb\qbittorrent-torrents-exporter.exe
github.com/ludoux/qbittorrent-torrents-exporter v0.3.1
qBittorrent host url(ex http://127.0.0.1:6363 ):http://****
qBittorrent username:****
qBittorrent password:****
panic: runtime error: index out of range [8] with length 0

goroutine 1 [running]:
main.getTrackerHost({0xc000278b40, 0x82})
        /github/workspace/main.go:82 +0x6b0
main.genMap({0xc000014160, 0x1a}, {0xc00000e110, 0xf}, {0xc000016078, 0x12})
        /github/workspace/main.go:170 +0x6fd
main.main()
        /github/workspace/main.go:573 +0x45e
```

https://github.com/ludoux/qbittorrent-torrents-exporter/issues/10#issue-1453296161

### 代码定位：
https://github.com/ludoux/qbittorrent-torrents-exporter/blob/1052c4704b651a9b1b59596d8f977248e1ac2150/main.go#L82

### 目前进展：
0.3.4 新引进的 Debug 输出有点问题，目前还不能定位情况。后续发版 0.3.5 修订一下

### 怀疑：
1. tracker 有没有考虑到的情况，致使 getTrackerHost 分析出问题

**Comment by LoneFireBlossom** [comment]
使用0.3.5版本直接运行成功，导出种子成功没有报错

**Comment by ludoux** [comment]
> 使用0.3.5版本直接运行成功，导出种子成功没有报错

感谢，应该是某一个种子丢失了 tracker，旧版本没有考虑到这种情况。假如没有什么问题我就关 issue 啦，谢谢你这段时间的帮忙
