### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by fansi2020** [ludoux/qbittorrent-torrents-exporter#15]
I type in the webui address ---> enter username and password
---
Terminal error：

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.genMap({0xc00009a590, 0xe}, {0xc00009a5c0, 0x5}, {0xc00009a5e8, 0x6})
        /github/workspace/main.go:142 +0xb5b
main.main()
        /github/workspace/main.go:573 +0x45e

**Comment by ludoux** [comment]
#7 
This may happens when the qB url doesn't start with `http://` or `https://`.
