### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by atlantis414** [ludoux/qbittorrent-torrents-exporter#16]
github.com/ludoux/qbittorrent-torrents-exporter v0.3.5
New version found!
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.genMap({0xc000010200, 0x1a}, {0x0, 0x0}, {0x0, 0x0})
        /github/workspace/main.go:152 +0xbaf
main.main()
        /github/workspace/main.go:623 +0x81e

![1234](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/5257804/da43a92f-d688-461e-ab32-5d3359693d1e)

**Comment by atlantis414** [comment]
qb 是 4.3.9

**Comment by ludoux** [comment]
目前来看好像是 exporter 不能从 qB API中拿到种子任务列表。你方便把 qB 针对本 IP 的免密登录打开，然后只使用 -qh 参数运行么。因为代码没有怎么处理错误，我也不知道是不是没有登录成功😂

**Comment by atlantis414** [comment]
免密就可以了, 但是我使用的admin/adminadmin 是正确的, 其他软件访问也用了. 😂
关闭免密, 只输入 qbittorrent-torrents-exporter -qh "http://192.168.2.130:48080" ,出线错误:
`panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.genMap({0xc0000a40a0, 0x1a}, {0x0, 0x0}, {0x0, 0x0})
        /github/workspace/main.go:152 +0xbaf
main.main()
        /github/workspace/main.go:623 +0x81e`

预期应该出现输入用户名,密码提示? 

我的问题解决, thanks

**Comment by ludoux** [comment]
确实，这个其实蛮简陋的😂
________________________________
