### ISSUE TITLE
标签过滤器（tagFilter）可以恢复到原来的样子吗？给导出的任务添加标签-留空直接enter导出不了 程序过程可以在精细一点吗？

### ISSUE THREAD

**Issue by 54Jezz** [ludoux/qbittorrent-torrents-exporter#17]
![屏幕截图 2024-01-12 161104](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/138966247/7384d0ae-2e0a-4122-814b-4ccb39b05f3d)

用的这个指令：./qbittorrent-torrents-exporter.exe

**Comment by ludoux** [comment]
请问是只使用了 `categoryFilter` 分类筛选么。方便测试一下不使用任何筛选，即输入完地址、用户名、密码后一路回车导出么，理论上最后那个添加标签留空是可以导出的。

方便提供一下 qB 版本号，以及如下的界面么（敏感信息可以打码），我这边复测一下。
![图片](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/13460812/b190ee0e-348f-4d8e-915f-8b7dac829816)

这个工具确实比较粗糙😂

-----

我这边用如下的任务结构和指令在4.5.5上可以导出
![图片](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/13460812/e4d34e28-1f54-43a4-b1ca-7914025e23ad)

**Comment by 54Jezz** [comment]
![屏幕截图 2024-01-12 165312](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/138966247/14678173-0a13-48bc-bd58-fdff4c14e647)
![屏幕截图 2024-01-12 164806](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/138966247/798574db-9956-4043-9c95-9b764931aef5)
![屏幕截图 2024-01-12 165506](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/138966247/312a26b0-5c0b-44c7-b79a-b97c1319e53c)

导出来了 但只有8个 并没有像上述所说显示有9个 且希望能够有解决导出是没有标签的文件：
![屏幕截图 2024-01-12 165850](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/138966247/257b90c8-7679-479b-bf46-a7ffc6645632)

**Comment by ludoux** [comment]
![图片](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/13460812/de5fa961-83e2-46f6-8af1-a614f1688f7b)

我怀疑无法导出的那个任务是空tracker的，目前本软件还没法导出空tracker的任务(#12 )。你方便去 qB UI上面看一下这个任务的具体信息么。假如是空tracker的话，目前是无法导出的，非常抱歉。假如是有tracker的话，方便看看这个tracker信息和别的有没有什么不同么，因为软件的这块bug比较多
![图片](https://github.com/ludoux/qbittorrent-torrents-exporter/assets/13460812/45d048f2-8c09-47d7-89b3-d452614134ee)

**Comment by ludoux** [comment]
此外，enhanced edition未经过测试，因此表现也可能会有不同

**Comment by ludoux** [comment]
0.4.0 理论上支持了空tracker且优化了trackerhost识别，后续若有相关需求欢迎使用新版本测试，多谢
