### ISSUE TITLE
4.3.9版本软件1800个种子导出失败

### ISSUE THREAD

**Issue by host2318** [ludoux/qbittorrent-torrents-exporter#18]
该qb服务器在一千个种子时导出是正常的。现在种子更多，例行备份，发现导出失败，通过cmd运行，打印记录如下：
在get1000~1200随机失败

`github.com/ludoux/qbittorrent-torrents-exporter v0.3.5
New version found!
qBittorrent host url(ex http://127.0.0.1:6363 ):http://192.168.1.246:8989
qBittorrent username:admin
qBittorrent password:adminadmin
get torrents: 1~100
get torrents: 101~200
get torrents: 201~300
get torrents: 301~400
get torrents: 401~500
get torrents: 501~600
get torrents: 601~700
get torrents: 701~800
get torrents: 801~900
get torrents: 901~1000
get torrents: 1001~1100
get torrents: 1101~1200
panic: runtime error: index out of range [8] with length 0

goroutine 1 [running]:
main.getTrackerHost({0xc000354000, 0x1687})
        /github/workspace/main.go:90 +0x83f
main.genMap({0xc0000ae020, 0x19}, {0xc0000aa0b0, 0x5}, {0xc0000aa0f0, 0xa})
        /github/workspace/main.go:182 +0x6fd
main.main()
        /github/workspace/main.go:623 +0x81e`

**Comment by ludoux** [comment]
简单看了一下问题还是出现在tracker分析部分。假如使用本软件的用途是导出所有的种子的话，可以尝试增加参数 `-disableAnalize`，这样子就不会分析tracker并分类了，理论上不会影响其他功能。只能说这个小工具做的比较粗糙🤣后续有空可能会优化一下出错不要闪退

**Comment by host2318** [comment]
> 简单看了一下问题还是出现在tracker分析部分。假如使用本软件的用途是导出所有的种子的话，可以尝试增加参数 `-disableAnalize`，这样子就不会分析tracker并分类了，理论上不会影响其他功能。只能说这个小工具做的比较粗糙🤣后续有空可能会优化一下出错不要闪退

通过你的提示，做了删除动作，删除几个普通种子（**里面附加了很多tracker服务器链接**）。
保留PT的种子，已经导出成功。谢谢

C:\Users\WDAGUtilityAccount\Downloads\PT\export

10/20/2024  07:16 PM    <DIR>          .
10/20/2024  07:16 PM    <DIR>          ..
10/20/2024  07:16 PM    <DIR>          #Downloads#down2#
10/20/2024  07:16 PM    <DIR>          #Downloads#movie#
10/20/2024  07:16 PM    <DIR>          #Downloads#music#
10/20/2024  07:16 PM    <DIR>          #Downloads#tv#

1,825 个文件，54 个文件夹

**Comment by ludoux** [comment]
https://github.com/ludoux/qbittorrent-torrents-exporter/releases/tag/v0.4.0 。最新版本优化了一下识别，假如后续有导出需求的话可以试着使用新版本（不用加那两个新的参数），谢谢
