### ISSUE TITLE
Linux运行报错

### ISSUE THREAD

**Issue by henry-tujia** [ludoux/qbittorrent-torrents-exporter#2]
## 运行说明

- [x] 程序目录放置正确
- [x] qbi版本：4.4.2，满足要求

## 报错说明

 使用命令`./qbittorrent-torrents-exporter -qh "http://192.168.2.6:8080" -qu "admin" -qp "********" -githubchannel`，后出现以下错误
```bash
github.com/ludoux/qbittorrent-torrents-exporter v0.1.5
New version found!
get torrents: 1~100
get torrents: 101~118
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.getTrackerHost({0xc0004312c0, 0x2a})
        /github/workspace/main.go:70 +0x205
main.genMap({0x7ffe3c555d4d, 0x17}, {0x7ffe3c555d69, 0x5}, {0x7ffe3c555d73, 0xa})
        /github/workspace/main.go:130 +0x6da
main.main()
        /github/workspace/main.go:509 +0x45e
```

**Comment by ludoux** [comment]
应该是提取 tracker 主域名的时候出现错误了，请问方不方便截图一下 qbittorrent 主页面，左下角的 tracker 图？假如是 PT Tracker 的话，域名可以部分打码，但是分割符 `.` 不要打码掉，谢谢

**Comment by ludoux** [comment]
https://github.com/XIU2/TrackersListCollection

现有的程序对如上类型的 BT 公开 tracker 支持不佳，假如你是添加了类似 tracker 的话，可以等几天内的下一次更新即可。假如不是的话，麻烦如上提供一下信息。

**Comment by ludoux** [comment]
由于未活动，关闭此 issue。假如新版本还有类似问题重开此issue即可。

**Comment by henry-tujia** [comment]
> https://github.com/ludoux/qbittorrent-torrents-exporter/releases/tag/v0.2.1
> 
> 新的版本请尝试一下，修复了可能的问题

好的好的，最近有点忙，谢谢您！！！
