### ISSUE TITLE
windows客户端输入命令后就退出去了

### ISSUE THREAD

**Issue by laobanbiefangcu** [ludoux/qbittorrent-torrents-exporter#4]
是我打的命令不对吗， 还是哪里操作不对？没有提示报错原因，就是退出去了
<a href="https://sm.ms/image/stXVokuzmq1eUj7" target="_blank"><img src="https://s2.loli.net/2022/05/07/stXVokuzmq1eUj7.png" /></a>
<a href="https://sm.ms/image/DoE5tfZJRyGchYr" target="_blank"><img src="https://s2.loli.net/2022/05/07/DoE5tfZJRyGchYr.png" /></a>
<a href="https://sm.ms/image/awJPtZSlo5kzNs9" target="_blank"><img src="https://s2.loli.net/2022/05/07/awJPtZSlo5kzNs9.png" /></a>
<a href="https://sm.ms/image/5PLsHpgml4EfzKY" target="_blank"><img src="https://s2.loli.net/2022/05/07/5PLsHpgml4EfzKY.png" /></a>

**Comment by ludoux** [comment]
qbittorrent-torrents-exporter.exe 和 BT_backup 相对位置不对，应该是如下图的结构
![圖片](https://user-images.githubusercontent.com/13460812/167232603-afc2db57-41fd-4a4c-acaa-cda806ef158b.png)

此外，麻烦再检查一下可能的一下问题
1. qbittorrent Web API 要开启
2. 建议把 BT_backup 复制出来放到 D 盘一类的，再按上图放置导出工具，以免涉及到 C 盘权限问题
3.  -fc "E:\pt" 是指定需要导出的分类，建议先不使用此功能，先确保不筛选可以导出

谢谢！

**Comment by laobanbiefangcu** [comment]
> qbittorrent-torrents-exporter.exe 和 BT_backup 相对位置不对，应该是如下图的结构 ![圖片](https://user-images.githubusercontent.com/13460812/167232603-afc2db57-41fd-4a4c-acaa-cda806ef158b.png)
> 
> 此外，麻烦再检查一下可能的一下问题
> 
> 1. qbittorrent Web API 要开启且要运行
> 2. 建议把 BT_backup 复制出来放到 D 盘一类的，再按上图放置导出工具，以免涉及到 C 盘权限问题
> 3. -fc "E:\pt" 是指定需要导出的分类，建议先不使用此功能，先确保不筛选可以导出
> 
> 谢谢！
你好，1，qbittorrent Web API 已运行，2，还是以上问题，命令运行后就闪退，3.webui打开是错误种子是因为我把unraid里qb里的BT_backup目录复制出来，想在windows上导出种子
<a href="https://sm.ms/image/kWML2ht9qiGFDSl" target="_blank"><img src="https://s2.loli.net/2022/05/07/kWML2ht9qiGFDSl.png" /></a>
<a href="https://sm.ms/image/FrdgkZ7fojMH6EP" target="_blank"><img src="https://s2.loli.net/2022/05/07/FrdgkZ7fojMH6EP.png" /></a>
<a href="https://sm.ms/image/v6Ylh12QToDVEr3" target="_blank"><img src="https://s2.loli.net/2022/05/07/v6Ylh12QToDVEr3.png" /></a>

**Comment by ludoux** [comment]
请尝试一下在文件夹空白处右键打开终端，之后在如下图运行程序。这样子出错后窗口不会关闭，会有错误信息
![圖片](https://user-images.githubusercontent.com/13460812/167234440-7d6f8f68-b655-41d5-a8cd-aab95569a800.png)
![圖片](https://user-images.githubusercontent.com/13460812/167234448-7117f44d-138d-46e3-81e0-a501520a53de.png)

或者 Win+S 搜索 “终端”，或者 Win+R运行 cmd，之后输入  `cd /d d:\路径` 类似的来切换终端路径到exporter 所在目录，之后再按上图那样子运行一下程序，谢谢！

**Comment by ludoux** [comment]
PS. 可以尝试着BT_backup 从 unraid 复制出来后，qb web 地址填写 unraid 里的 qb 地址看一下

**Comment by laobanbiefangcu** [comment]
你好，出现different trackerhost in the same torrent! Will use the last trackerhost for filter.错误

<a href="https://sm.ms/image/vu43JeLz8wrcVjP" target="_blank"><img src="https://s2.loli.net/2022/05/07/vu43JeLz8wrcVjP.png" /></a>

**Comment by ludoux** [comment]
您好，这是工具在分析tracker主域名中出现的错误，现在应该是有两个问题：
1. 报 different trackerhost in the same torrent! Will use the last trackerhost for filter 意味着软件认为此种子文件里面的有来自于多个域名的tracker,这在PT中是不应该发生的（BT可以忽略），但是软件正确处理了。
2. 闪退是其余解析出了问题。

https://ludoux.lanzoul.com/iWumA04f5yuj 或者 [debug1.zip](https://github.com/ludoux/qbittorrent-torrents-exporter/files/8644376/debug1.zip)（两者相同，您选择一个方便的下载方式即可）这个是针对的一个 debug 程序，它会在分析的时候打出更多的日志。请您下载然后按之前的操作再做一次，您需要关注：
1. 报 different trackerho
st in the same torrent! Will use the last trackerhost for filter 的时候，是不是真的有种子有多个tracker域名
2. 在 panic: runtime error

之前的一些输出

请在运行后将上面相关的截图贴上来，您可以把PT域名相关给部分打码（如 https://t.[打码].com/announce.php?passkey=[打码] ）。假如您觉得不方便，也可以程序全部的输出复制或者截图发送到我的邮箱 `chinaluchang[at]live.com` .`[at]`替换为 `@`

多谢！

**Comment by laobanbiefangcu** [comment]
你好，以下是部分日志，filelist存在两个tracker，club.hares.top这个白兔站解析不出来

PS C:\Users\505\AppData\Local\qBittorrent> ./debug1.exe
github.com/ludoux/qbittorrent-torrents-exporter v0.2.1
qBittorrent host url(ex http://127.0.0.1:6363 ):http://127.0.0.1:8080
qBittorrent username:admin
qBittorrent password:adminadmin
get torrents: 1~81
==https://tracker.totheglory.im/*****==
finished. result istotheglory.im
==https://tracker.m-team.cc/announce.php?passkey=***==
finished. result ism-team.cc
==https://tracker.hdchina.org/announce?credential=***&uid=***==
finished. result ishdchina.org
==https://ourbits.club/announce.php?passkey=***==
finished. result isourbits.club
==https://hdhome.org/announce.php?passkey=***==
finished. result ishdhome.org
==http://reactor.flro.org/****/announce|http://reactor.filelist.io/***/announce==
warning: different trackerhost in the same torrent! Will use the last trackerhost for filter.(pre is flro.org, cur is filelist.io
finished. result isfilelist.io
==https://tracker.totheglory.im/***==
finished. result istotheglory.im
==http://please.passthepopcorn.me:2710/***==
finished. result ispassthepopcorn.me
==https://announce.leaguehd.com/announce.php?passkey=***==
finished. result isleaguehd.com
==http://tracker.pterclub.com/announce?passkey=****==
finished. result ispterclub.com
==https://www.hdarea.co/announce.php?passkey=****==
finished. result ishdarea.co
==http://on.springsunday.net/announce.php?passkey=***==
finished. result isspringsunday.net
==https://chdbits.co/announce.php?passkey=***==
finished. result ischdbits.co
==http://reactor.filelist.io/***/announce|http://reactor.flro.org/***/announce==
warning: different trackerhost in the same torrent! Will use the last trackerhost for filter.(pre is filelist.io, cur is flro.org
finished. result isflro.org
==https://tracker.hdbits.org/announce.php?passkey=***==
finished. result ishdbits.org
==https://tracker.hdsky.me/announce.php?passkey=***==
finished. result ishdsky.me
==https://ourbits.club/announce.php?passkey=***==
finished. result isourbits.club
==http://announce.leaguehd.com/announce.php?passkey=***==
finished. result isleaguehd.com
==https://club.hares.top/announce.php?authkey=***==
err: matchs empty. trackers is https://club.hares.top/announce.php?authkey=***
panic: runtime error: index out of range [8] with length 0

goroutine 1 [running]:
main.getTrackerHost({0xc00000cb00, 0x3c})
        /home/luu/Documents/Git/qbittorrent-torrents-exporter/main.go:81 +0x7f0
main.genMap({0xc00000e678, 0x15}, {0xc000010b48, 0x5}, {0xc000010b80, 0xa})
        /home/luu/Documents/Git/qbittorrent-torrents-exporter/main.go:170 +0x6da
main.main()
        /home/luu/Documents/Git/qbittorrent-torrents-exporter/main.go:569 +0x45e

**Comment by ludoux** [comment]
是不是白兔的authkey 里面有特殊字符（斜杠，问号等非字母或数字）？方便把authkey处理一下（比如`sdfsg`一类的连续字母就用单一字母`a`代替，把一些数字替换成别的，就是把authkey处理一下和原本的不一样，但能体现大概的格式），然后回复给我么，谢谢

我这边以 `https://c[码]b.h[码]s.[码]p/announce.php?authkey=ddddddd` 来测试是可以正常识别出主域名的。

以及 filelist 那个 trackerhost 警告看来是正常的，忽略即可。

**Comment by laobanbiefangcu** [comment]
白兔的tracker地址是这样的

https://club.hares.top/announce.php?authkey=8888|8888|8w88WWw

**Comment by ludoux** [comment]
https://ludoux.lanzoul.com/isK4z04fbehc 请试一下这个新版本，这个应该可以正常导出了。假如可以的话，下一个版本会带上这个修复，多谢！

原因是 authkey 里面有 `|` ，软件也刚巧是用这个来作为tracker的分割符的

**Comment by laobanbiefangcu** [comment]
感谢，可以成功导出了！非常感谢大佬抽出时间帮忙！

**Comment by laobanbiefangcu** [comment]
请问下能否全部导出在一个总文件夹里，我看导出来是一个站一个文件夹

**Comment by ludoux** [comment]
> 请问下能否全部种子导出在一个总文件夹里，我看导出来是一个站一个文件夹

这个暂时还不行，不过你可以用搜索一类的把 export 文件夹下所有的种子给搜索导出来。
btw 请使用后最终再确认一下导出的 torrent 文件数目和添加进qb软件后，识别的tracker无误，这个工具没有经过非常广泛的测试 :)

**Comment by laobanbiefangcu** [comment]
> > 请问下能否全部种子导出在一个总文件夹里，我看导出来是一个站一个文件夹
> 
> 这个暂时还不行，不过你可以用搜索一类的把 export 文件夹下所有的种子给搜索导出来。 btw 请使用后最终再确认一下导出的 torrent 文件数目和添加进qb软件后，识别的tracker无误，这个工具没有经过非常广泛的测试 :)

好的，感谢回复

**Comment by ludoux** [comment]
新版应该修复了[ v0.3.0](https://github.com/ludoux/qbittorrent-torrents-exporter/releases/tag/v0.3.0)
