### ISSUE TITLE
有两个tracker的导入到qbit只有一个

### ISSUE THREAD

**Issue by junbluedd** [ludoux/qbittorrent-torrents-exporter#6]
如图，图下面的才是正常的种子，
![This is an image](https://pan.luweidan.top/upload/a5c639e53c77637ce01c9a7d1b2b48e9.png)
原本是ipv4加ipv6的tracker，导入到qbit网页端后就只显示一个ipv6了，但动漫花园之类的一个tracker的种子就是正常的

**Comment by ludoux** [comment]
这个请问你 qbit 版本是440+么。假如是的话，方便把bt_backup里面对应种子文件的.fastresume 拖进 https://chocobo1.github.io/bencode_online/ ，然后翻到类似 trackers 字段的地方，把域名和passkey打码后贴上来么。多tracker可能考虑得不是太成熟

假如不是440+，或者上面的.fastresume文件里面没有tracker相关，方便把bt_backup里面对应种子文件的.torrent 拖进 https://chocobo1.github.io/bencode_online/ ，然后翻到类似 announce 、 announce-list 字段的地方，把域名和passkey打码后贴上来么。多tracker可能考虑得不是太成熟

**Comment by ludoux** [comment]
已定位，请等待下一个版本修复

**Comment by ludoux** [comment]
新版应该已经修复了，请试用。仍有问题请 reopen,多谢 [v0.3.0](https://github.com/ludoux/qbittorrent-torrents-exporter/releases/tag/v0.3.0)
