### ISSUE TITLE
请问下如果是docker搭建qbittorrent该如何使用呢？

### ISSUE THREAD

**Issue by huanxiangyixia** [ludoux/qbittorrent-torrents-exporter#8]
![image](https://user-images.githubusercontent.com/54071554/179359414-c6b6f331-401f-4a87-b872-d0f4641db3a5.png)

**Comment by ludoux** [comment]
大同小异，将 docker 下的 bt_backup 文件夹复制出来即可。请截图  bt_backup 文件夹内容，以及 qB 版本号。

**Comment by ludoux** [comment]
exporter 要在 BT_backup 的上一个目录，请参考 https://github.com/ludoux/qbittorrent-torrents-exporter/issues/4#issuecomment-1120104511 。
以及为了避免可能的权限问题，建议将其下载到本机上再进行导出操作

**Comment by huanxiangyixia** [comment]
感谢指导，确实是exporter 放在BT_backup目录内的原因，现已解决！

**Comment by ludoux** [comment]
好，请注意检查导出数目以及种子 tracker 信息是否正确，先关闭 issue 了😆
